name: qiita_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"


dependencies:

  flutter:
    sdk: flutter
  http: ^1.2.1

 




dev_dependencies:

  flutter_test:
    sdk: flutter




flutter:
  assets:
    - images/
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf